Python/django/hello_world/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),#first load this by ROOT_URLCONF, then to polls/urls
    path('admin/', admin.site.urls),
]

Python/django/hello_world/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/ is int and it is quesion_id
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Python/django/hello_world/mysite/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

Python/django/hello_world/mysite/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from .models import Question

from django.template import loader



def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

# Note that once we’ve done this in all these views, we no longer need to 
# import loader and HttpResponse 
# (you’ll want to keep HttpResponse if you still 
# have the stub methods for detail, results, and vote).

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)
# Create your views here.

def question_list(request):
    questions = Question.objects.all()
    return render(request, 'index.html',{'question_list': questions})

Python/django/hello_world/mysite/polls/templates/polls/detail.html
<!DOCTYPEhtml><html><head><metacharset="utf-8"></head><body><h1>Question List</h1>    {% if question_list %}<ul>        {% for question in question_list %}<li><ahref="detail/{{ question.id }}"> {{ question.question_text }} </a></l        {% endfor %}</ul>    {% else %}<p>No question to vote.</p>    {% endif %}</body></html>

Python/django/hello_world/mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}