Python/2019011325_jiangcan_hw4/src/mysite/deeplearning/urls.py
from django.urls import path

from . import views

app_name = 'deeplearning'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('<int:project_id>/', views.detail, name='detail'),
    path('results/', views.results, name='results'),
]

Python/2019011325_jiangcan_hw4/src/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from deeplearning import views


urlpatterns = [
    path('deeplearning/', include('deeplearning.urls')),
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
]

Python/2019011325_jiangcan_hw4/src/mysite/deeplearning/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text


class MachineLearningManager(models.Manager):
    def create_model(self, model_name, sponsor_name, sponsor_time, complete_time, train_status, train_duration,
                     train_console):
        mlm = self.create(model_name=model_name, sponsor_name=sponsor_name, sponsor_time=sponsor_time,
                          complete_time=complete_time, train_status=train_status, train_duration=train_duration,
                          train_console=train_console)
        # do something with the model
        return mlm


class MachineLearningModel(models.Model):
    model_name = models.CharField(max_length=20)
    sponsor_name = models.CharField(max_length=20)
    sponsor_time = models.DateTimeField('when training begins')
    complete_time = models.DateTimeField('when training completes', default=datetime.datetime.now())
    train_status = models.BooleanField('whether training completes')
    train_duration = models.IntegerField('how long the training lasts')
    train_console = models.CharField('Console', max_length=2000)

    objects = MachineLearningManager()

    def __str__(self):
        return self.model_name

Python/2019011325_jiangcan_hw4/src/mysite/deeplearning/views.py
import datetime
import threading

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Question, Choice, MachineLearningModel, MachineLearningManager
from datetime import datetime

import torch
import torchvision

from models.lenet import LeNet
from utils import pre_process

import numpy as np

from torchvision import transforms

def get_data_loader(batch_size):
    # MNIST dataset
    train_dataset = torchvision.datasets.MNIST(root='data/',
                                               train=True,
                                               transform=pre_process.data_augment_transform(),
                                               download=True)

    test_dataset = torchvision.datasets.MNIST(root='data/',
                                              train=False,
                                              transform=pre_process.normal_transform())

    # Data loader
    train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                               batch_size=batch_size,
                                               shuffle=True)

    test_loader = torch.utils.data.DataLoader(dataset=test_dataset,
                                              batch_size=batch_size,
                                              shuffle=False)

    return train_loader, test_loader


def evaluate(model, test_loader, device):
    model.eval()
    with torch.no_grad():
        correct = 0
        total = 0
        for images, labels in test_loader:
            images = images.to(device)
            labels = labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        print('Test Accuracy of the model is: {} %'.format(100 * correct / total))


def save_model(model, save_path='lenet.pth'):
    ckpt_dict = {
        'state_dict': model.state_dict()
    }
    torch.save(ckpt_dict, save_path)


def train(epochs, batch_size, learning_rate, num_classes, Model):
    # fetch data
    train_loader, test_loader = get_data_loader(batch_size)

    # Loss and optimizer
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    model = LeNet(num_classes).to(device)
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

    # fetch console
    console_in_django = ''

    # start train
    total_step = len(train_loader)
    for epoch in range(epochs):
        for i, (images, labels) in enumerate(train_loader):

            # get image and label
            images = images.to(device)
            labels = labels.to(device)

            # Forward pass
            outputs = model(images)
            loss = criterion(outputs, labels)

            # Backward and optimize
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            if (i + 1) % 100 == 0:
                print('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'
                      .format(epoch + 1, epochs, i + 1, total_step, loss.item()))
                # write in console
                data = loss.item()
                data = format(data, '.4f')
                data = str(data)
                Model.train_console = Model.train_console + '/' + data
                Model.save()
                # may cut off a null str

        # evaluate after epoch train
        evaluate(model, test_loader, device)

    # save the trained model and console
    save_model(model, save_path='lenet.pth')
    return model


def index(request):
    # TODO 添加多线程算法 muti-threading
    
    if request.method == 'POST':
        # thread2 = threading.Thread(target=jump_result(request))
        # thread1 = threading.Thread(target=begin_learning(request))
        # x = thread2.start()
        # thread1.join()
        # return x
        print("I've receive the command.")
        # create your model and save it now!
        model_name = request.POST.get('model_name')
        sponsor_name = request.POST.get('sponsor_name')
        sponsor_time = datetime.now()
        complete_time = datetime.now()
        train_status = False
        train_duration = 0
        train_console = ''
        # remember to update the console
        Model = MachineLearningModel.objects.create_model(model_name, sponsor_name, sponsor_time, complete_time,
                                                          train_status, train_duration, train_console)
        train(10, 256, 0.001, 10, Model)
        Model.complete_time = datetime.now()
        Model.train_status = True
        Model.save()
        return HttpResponseRedirect(reverse('deeplearning:results'))
    else:
        # if there be a multi-thread operation, it should be here
        print("it is get.")
        # return HttpResponseRedirect(reverse('deeplearning:results'))

        return render(request, 'deeplearning/index.html')

# begin train
# def begin_learning(request):
#     print("begin training!")
#     # create your model and save it now!
#     model_name = request.POST.get('model_name')
#     sponsor_name = request.POST.get('sponsor_name')
#     sponsor_time = datetime.now()
#     complete_time = datetime.now()
#     train_status = False
#     train_duration = 0
#     train_console = ''
#     # remember to update the console
#     Model = MachineLearningModel.objects.create_model(model_name, sponsor_name, sponsor_time, complete_time,
#                                                         train_status, train_duration, train_console)
#     train(10, 256, 0.001, 10, Model)
#     Model.complete_time = datetime.now()
#     Model.train_status = True
#     Model.save()
#     return HttpResponseRedirect(reverse('deeplearning:results'))

# jump to the result
# def jump_result(request):
#     print("success jump!")
#     return HttpResponseRedirect(reverse('deeplearning:results'))

def detail(request, project_id):
    # may be some try and except module?
    train_project = get_object_or_404(MachineLearningModel, pk=project_id)
    try:
        if not train_project.train_status:
            train_project.train_duration = (datetime.now() - train_project.sponsor_time).seconds
            train_project.save()
        else:
            train_project.train_duration = (train_project.complete_time - train_project.sponsor_time).seconds
            train_project.save()
    except KeyError:
        train_project.sponsor_time = timezone.now()
        train_project.train_duration = 0
        train_project.save()
    train_console = train_project.train_console
    train_console = train_console.split('/')
    train_console = train_console[1:]
    train_console_length = len(train_console)
    train_completed = train_project.complete_time
    context = {
        'train_project': train_project,
        'train_completed': train_completed,
        'train_console': train_console,
        'train_console_length': train_console_length,
    }
    return render(request, 'deeplearning/detail.html', context)


def results(request):
    project_list = MachineLearningModel.objects.all()
    project_list = list(project_list)
    context = {'project_list': project_list}
    return render(request, 'deeplearning/results.html', context)


def home(request):
    return render(request, 'deeplearning/home.html')

Python/2019011325_jiangcan_hw4/src/mysite/deeplearning/templates/deeplearning/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% load static %}
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'deeplearning/detail.css' %}"> -->
    </head>
    <body>
        {% csrf_token %}
        <h1>项目名称：<p>{{ train_project.model_name }}</p></h1>
        <div><h2>ID: </h2><p>{{ train_project.sponsor_name }}</p></div>
        <div><h2>Time: </h2><p>{{ train_project.sponsor_time }}</p></div>
        <div><h2>运行时长：</h2><p>{{ train_project.train_duration }}s</p></div>
        {% if train_project.train_status %}
        <div><h2>完成时间：</h2><p>{{ train_completed }}</p></div>
        {% endif %}
        {% if train_project.train_status %}
        <div><h2>项目状态：</h2><p>已完成</p></div>
        {% else %}
        <div><h2>项目状态：</h2><p>进行中</p></div>
        {% endif %}
        <!-- {% if not train_project.train_status %} -->
        <div><h2>日志（loss/eporch）：</h2></div>
        <div id="console">
            {% for data in train_console %}
            <p class="footsteps">{{ data }}>></p>
            {% endfor %}
        </div>
        <!-- {% endif %} -->
        <script type="text/javascript" src="{% static 'deeplearning/detail.js' %}"></script>
    </body>
</html>

Python/2019011325_jiangcan_hw4/src/mysite/deeplearning/templates/deeplearning/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="author" content="JC">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">

        <title>Create deeplearning Page</title>

        {% load static %}

         <!-- Bootstrap core CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'deeplearning/home.css' %}">
            <!-- Additional CSS Files -->
        
        <link rel="stylesheet" type="text/css" href="{% static 'deeplearning/fontawesome.css' %} ">
        <link rel="stylesheet" href="{% static 'deeplearning/templatemo-liberty-market.css' %}">
        <link rel="stylesheet" href="{% static 'deeplearning/owl.css' %}">
        <link rel="stylesheet" href="{% static 'deeplearning/animate.css' %}">
        <link rel="stylesheet" href="{% static 'deeplearning/swiper-bundle.min.css' %}"/>
    </head>
<body>

  <!-- ***** Header Area Stasrt ***** -->
  <header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li>Author:江灿</li>
                        <li><a href="https://github.com/Jc-Bravo">Github</a></li>
                        <li>邮件:jc.thucs@gmail.com</li>
                        <li><a href="create.html" class="active">Create Yours</a></li>
                    </ul>   
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
  </header>
  <div class="page-heading normal-space">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <h6>THU</h6>
          <h2>Create Your Deeplearning Now.</h2>
          <!-- <span>Home > <a href="#">Create Yours</a></span> -->
          <div class="buttons">
            <div class="main-button">
              <a href="http://127.0.0.1:8000/deeplearning/index/">训练页面</a>
            </div>
            <div class="border-button">
              <a href="http://127.0.0.1:8000/deeplearning/results/">结果展示页面</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="item-details-page">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="section-heading">
            <div class="line-dec"></div>
            <h2>Apply For <em>Your deeplearning</em> Here.</h2>
          </div>
        </div>
      </div>
    </div>
  </div>

        <footer>
            <div class="container">
              <div class="row">
                <div class="col-lg-12">
                  <p>
                  Copyright &copy; 2022.Company name All rights reserved.</p>
                </div>
              </div>
            </div>
          </footer>
        <script type="text/javascript" src="{% static 'deeplearning/custom.js' %}"></script>
        <script type="text/javascript" src="{% static 'deeplearning/home.js' %}"></script>
        <script type="text/javascript" src="{% static 'deeplearning/isotope.js' %}"></script>
        <script type="text/javascript" src="{% static 'deeplearning/isotope.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'deeplearning/owl-carousel.js' %}"></script>
        <script type="text/javascript" src="{% static 'deeplearning/popup.js' %}"></script>

        <script type="text/javascript" src="{% static 'deeplearning/tabs.js' %}"></script>

        <script type="text/javascript" src="{% static 'deeplearning/wow.js' %}"></script>

</body>
</html>

Python/2019011325_jiangcan_hw4/src/mysite/deeplearning/templates/deeplearning/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="author" content="JC">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
        
        {% load static %}
           <!-- Bootstrap core CSS -->
           <link rel="stylesheet" type="text/css" href="{% static 'deeplearning/home.css' %}">
           <!-- Additional CSS Files -->
       
       <link rel="stylesheet" type="text/css" href="{% static 'deeplearning/fontawesome.css' %} ">
       <link rel="stylesheet" href="{% static 'deeplearning/templatemo-liberty-market.css' %}">
       <link rel="stylesheet" href="{% static 'deeplearning/owl.css' %}">
       <link rel="stylesheet" href="{% static 'deeplearning/animate.css' %}">
       <link rel="stylesheet" href="{% static 'deeplearning/swiper-bundle.min.css' %}"/>
   </head>
    <body>
        <form action="{% url 'deeplearning:index' %}" id="costom" method="post">
            {% csrf_token %}
            <label id="name_label"  for="sponsor_name">ID:</label>
            <input id="sponsor_name" placeholder="1-9a-z" name="sponsor_name" type="text">
            <br />
            <label id="model_label" for="model_name">Project:</label>
            <input id="model_name" placeholder="1-9a-z" name="model_name" type="text">
            <input type="submit" >
        </form>          
          <div class="page-heading normal-space">
            <div class="container">
              <div class="row">
                <div class="col-lg-12">
                  <h6>THU</h6>
                  <h2>Create Your Deeplearning Now.</h2>
                  <!-- <span>Home > <a href="#">Create Yours</a></span> -->
                  <div class="buttons">
                    <div class="main-button">
                      <a href="http://127.0.0.1:8000/">返回主页</a>
                    </div>
                    <div class="border-button">
                      <a href="http://127.0.0.1:8000/deeplearning/results/">结果展示页面</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <footer>
            <div class="container">
              <div class="row">
                <div class="col-lg-12">
                  <p>
                  Copyright &copy; 2022.Company name All rights reserved.</p>
                </div>
              </div>
            </div>
          </footer>
        <script type="text/javascript" src="{% static 'deeplearning/index.js' %}"></script>
    </body>
</html>


Python/2019011325_jiangcan_hw4/src/mysite/deeplearning/templates/deeplearning/results.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="author" content="JC">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">

        <title>Create deeplearning Page</title>

        {% load static %}

         <!-- Bootstrap core CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'deeplearning/home.css' %}">
            <!-- Additional CSS Files -->
        
        <link rel="stylesheet" type="text/css" href="{% static 'deeplearning/fontawesome.css' %} ">
        <link rel="stylesheet" href="{% static 'deeplearning/templatemo-liberty-market.css' %}">
        <link rel="stylesheet" href="{% static 'deeplearning/owl.css' %}">
        <link rel="stylesheet" href="{% static 'deeplearning/animate.css' %}">
        <link rel="stylesheet" href="{% static 'deeplearning/swiper-bundle.min.css' %}"/>
        <!-- <link rel="stylesheet" href="{% static 'deeplearning/results.css' %} "> -->

    </head>
    <body>
        <h1 id="training">训练中</h1>
        {% csrf_token %}
        {% for project in project_list %}
        {% if not project.train_status %}
            <div class="project{{ forloop.counter }}">
                <div>
                    <a href="{% url 'deeplearning:detail' project.id %}">ID: {{project.model_name}}</a>
                </div>
                <div><label>ID: </label><p>{{ project.sponsor_name }}</p></div>
                <div><label>TIME: </label><p>{{ project.sponsor_time }}</p></div>
                </br>
            </div>
            <div class="cutoff"></div>
        {% endif %}
        {% endfor %}
        <h1 id="trained">已完成</h1>
        {% csrf_token %}
        {% for project in project_list %}
        {% if project.train_status %}
            <div class="project{{ forloop.counter }}">
                <div><a href="{% url 'deeplearning:detail' project.id %}">{{project.model_name}}</a></div>
                <div><label>ID</label><p>{{project.sponsor_name}}</p></div>
                <div><label>TIME:</label><p>{{project.sponsor_time}}</p></div>
                </br>
            </div>
            <div class="cutoff"></div>
        {% endif %}
        {% endfor %}
        
        <footer>
            <div class="container">
              <div class="row">
                <div class="col-lg-12">
                  <p>
                  Copyright &copy; 2022.Company name All rights reserved.</p>
                </div>
              </div>
            </div>
          </footer>
        <script type="text/javascript" src="{% static 'deeplearning/results.js' %}"></script>
    </body>
</html>